Bump Rust edition to 2024
The following issues were flagged by `cargo fix --edition`:

- `impl-trait-overcaptures` (RPIT lifetime capture change):
`shutdown::on_error` captured the liftime of `&self` under 2024, resulting in:

```
error[E0597]: `shutdown_tx` does not live long enough
   --> src/main.rs:107:22
    |
 57 |     let (shutdown_tx, shutdown_rx) =
    |          ----------- binding `shutdown_tx` declared here
...
107 |         tokio::spawn(shutdown_tx.on_error(rabbitmq.run(state))),
    |         -------------^^^^^^^^^^^-------------------------------
    |         |            |
    |         |            borrowed value does not live long enough
    |         argument requires that `shutdown_tx` is borrowed for `'static`
...
119 | }
    | - `shutdown_tx` dropped here while still borrowed
    |
note: requirement that the value outlives `'static` introduced here
   --> /home/elev3n/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.34.0/src/task/spawn.rs:166:28
    |
166 |         F: Future + Send + 'static,
    |                            ^^^^^^^
note: this call may capture more lifetimes than intended, because Rust 2024 has adjusted the `impl Trait` lifetime capture rules
   --> src/main.rs:107:22
    |
107 |         tokio::spawn(shutdown_tx.on_error(rabbitmq.run(state))),
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: you could use a `use<...>` bound to explicitly specify captures, but argument-position `impl Trait`s are not nameable
   --> src/shutdown.rs:47:14
    |
 47 |         fut: impl Future<Output = Result<T, E>>,
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: use the precise capturing `use<...>` syntax to make the captures explicit
   --> src/shutdown.rs:45:25
    |
 45 ~     pub fn on_error<T, E, U: Future<Output = Result<T, E>>>(
 46 |         &'_ self,
 47 ~         fut: U,
 48 ~     ) -> impl Future<Output = Result<T, E>> + use<T, E, U> {

```

  We fix that, by changing APIT to named `U: Future<...>` and added
  precise capture `+ use<T, E, U>` so the returned future does not
  capture `&self`.
  https://doc.rust-lang.org/edition-guide/rust-2024/rpit-lifetime-capture.html

-  `if_let_rescope`: Rust 2024 changes temporary lifetime scope in `if
   let`/`else` blocks:
   https://doc.rust-lang.org/edition-guide/rust-2024/temporary-if-let-scope.html
   `cargo fix` rewrote one site in `src/handlers.rs` to use `match`:

```
            if let Some(receiver) = client.queue.wait_for_events() {
                (queue_id, receiver)
            } else {
                let events = client.queue.peek_events(args.last_event_id);
                return Ok(get_events_response(events, queue_id));
            }

```
   We reject that rewrite, the new behavior is irrelevant for this block.

- `tail-expr-drop-order`: Rust 2024 changes relative drop order for tail-expression temporaries vs locals.

  https://doc.rust-lang.org/edition-guide/rust-2024/temporary-tail-expr-scope.html

  The following warning was flagged:
```
warning: relative drop order changing in Rust 2024
   --> src/handlers.rs:260:64
    |
248 |     let db = state.db_pool.get().await?;
    |         --
    |         |
    |         `db` calls a custom destructor
    |         `db` will be dropped later as of Edition 2024
249 |     let sql = "SELECT realm_id FROM zerver_userprofile WHERE id = $1";
250 |     let Some(session_row) = db.query_opt(sql, &[&user_profile_id]).await? else {
    |              -----------
    |              |
    |              `session_row` calls a custom destructor
    |              `session_row` will be dropped later as of Edition 2024
...
260 |     get_events_backend(state, user_profile_id, realm_id, args).await
    |                                                                ^^^^^
    |                                                                |
    |                                                                this value will be stored in a temporary; let us call it `#1`
    |                                                                up until Edition 2021 `#1` is dropped last but will be dropped earlier in Edition 2024
261 | }
    | - now the temporary value is dropped here, before the local variables in the block or statement
    |
    = warning: this changes meaning in Rust 2024
    = note: for more information, see <https://doc.rust-lang.org/edition-guide/rust-2024/temporary-tail-expr-scope.html>

```

  Correctness of this code doesn't depend on drop order, so no change is
  needed.